use crate::civ::civ_identity::BuiltinCiv;
use crate::civ::great_works::GreatWorkSlotType;
use crate::game::state::BuildingDef;
use crate::game::IdGenerator;
use crate::{YieldBundle, YieldType};

/// Returns all base-game building definitions.
pub fn builtin_building_defs(id_gen: &mut IdGenerator) -> Vec<BuildingDef> {
    vec![
        // ── City Center Buildings (8) ────────────────────────────────────────
        BuildingDef {
            id: id_gen.next_building_id(),
            name: "Monument",
            cost: 60,
            maintenance: 0,
            yields: YieldBundle::new().with(YieldType::Culture, 2),
            requires_district: Some("City Center"),
            great_work_slots: vec![],
            exclusive_to: None,
            replaces: None,
        },
        BuildingDef {
            id: id_gen.next_building_id(),
            name: "Palace",
            cost: 1,
            maintenance: 0,
            yields: YieldBundle::new()
                .with(YieldType::Gold, 5)
                .with(YieldType::Culture, 2)
                .with(YieldType::Science, 2)
                .with(YieldType::Production, 2)
                .with(YieldType::Housing, 1)
                .with(YieldType::Amenities, 1),
            requires_district: Some("City Center"),
            great_work_slots: vec![],
            exclusive_to: None,
            replaces: None,
        },
        BuildingDef {
            id: id_gen.next_building_id(),
            name: "Granary",
            cost: 65,
            maintenance: 0,
            yields: YieldBundle::new()
                .with(YieldType::Food, 1)
                .with(YieldType::Housing, 2),
            requires_district: Some("City Center"),
            great_work_slots: vec![],
            exclusive_to: None,
            replaces: None,
        },
        BuildingDef {
            id: id_gen.next_building_id(),
            name: "Walls",
            cost: 80,
            maintenance: 0,
            yields: YieldBundle::new(),
            requires_district: Some("City Center"),
            great_work_slots: vec![],
            exclusive_to: None,
            replaces: None,
        },
        BuildingDef {
            id: id_gen.next_building_id(),
            name: "Water Mill",
            cost: 80,
            maintenance: 0,
            yields: YieldBundle::new()
                .with(YieldType::Food, 1)
                .with(YieldType::Production, 1),
            requires_district: Some("City Center"),
            great_work_slots: vec![],
            exclusive_to: None,
            replaces: None,
        },
        BuildingDef {
            id: id_gen.next_building_id(),
            name: "Medieval Walls",
            cost: 225,
            maintenance: 0,
            yields: YieldBundle::new(),
            requires_district: Some("City Center"),
            great_work_slots: vec![],
            exclusive_to: None,
            replaces: None,
        },
        BuildingDef {
            id: id_gen.next_building_id(),
            name: "Renaissance Walls",
            cost: 305,
            maintenance: 0,
            yields: YieldBundle::new(),
            requires_district: Some("City Center"),
            great_work_slots: vec![],
            exclusive_to: None,
            replaces: None,
        },
        BuildingDef {
            id: id_gen.next_building_id(),
            name: "Sewer",
            cost: 200,
            maintenance: 0,
            yields: YieldBundle::new().with(YieldType::Housing, 2),
            requires_district: Some("City Center"),
            great_work_slots: vec![],
            exclusive_to: None,
            replaces: None,
        },
        // ── Campus Buildings (3) ─────────────────────────────────────────────
        BuildingDef {
            id: id_gen.next_building_id(),
            name: "Library",
            cost: 90,
            maintenance: 1,
            yields: YieldBundle::new().with(YieldType::Science, 2),
            requires_district: Some("Campus"),
            great_work_slots: vec![],
            exclusive_to: None,
            replaces: None,
        },
        BuildingDef {
            id: id_gen.next_building_id(),
            name: "University",
            cost: 250,
            maintenance: 2,
            yields: YieldBundle::new()
                .with(YieldType::Science, 4)
                .with(YieldType::Housing, 1),
            requires_district: Some("Campus"),
            great_work_slots: vec![],
            exclusive_to: None,
            replaces: None,
        },
        BuildingDef {
            id: id_gen.next_building_id(),
            name: "Research Lab",
            cost: 580,
            maintenance: 3,
            yields: YieldBundle::new().with(YieldType::Science, 5),
            requires_district: Some("Campus"),
            great_work_slots: vec![],
            exclusive_to: None,
            replaces: None,
        },
        // ── Holy Site Buildings (3) ──────────────────────────────────────────
        BuildingDef {
            id: id_gen.next_building_id(),
            name: "Shrine",
            cost: 70,
            maintenance: 1,
            yields: YieldBundle::new().with(YieldType::Faith, 2),
            requires_district: Some("Holy Site"),
            great_work_slots: vec![],
            exclusive_to: None,
            replaces: None,
        },
        BuildingDef {
            id: id_gen.next_building_id(),
            name: "Temple",
            cost: 120,
            maintenance: 2,
            yields: YieldBundle::new().with(YieldType::Faith, 4),
            requires_district: Some("Holy Site"),
            great_work_slots: vec![],
            exclusive_to: None,
            replaces: None,
        },
        BuildingDef {
            id: id_gen.next_building_id(),
            name: "Stave Church",
            cost: 120,
            maintenance: 2,
            yields: YieldBundle::new().with(YieldType::Faith, 4),
            requires_district: Some("Holy Site"),
            great_work_slots: vec![],
            exclusive_to: Some(BuiltinCiv::Norway),
            replaces: Some("Temple"),
        },
        // ── Commercial Hub Buildings (3) ─────────────────────────────────────
        BuildingDef {
            id: id_gen.next_building_id(),
            name: "Market",
            cost: 120,
            maintenance: 0,
            yields: YieldBundle::new().with(YieldType::Gold, 3),
            requires_district: Some("Commercial Hub"),
            great_work_slots: vec![],
            exclusive_to: None,
            replaces: None,
        },
        BuildingDef {
            id: id_gen.next_building_id(),
            name: "Bank",
            cost: 290,
            maintenance: 0,
            yields: YieldBundle::new().with(YieldType::Gold, 5),
            requires_district: Some("Commercial Hub"),
            great_work_slots: vec![],
            exclusive_to: None,
            replaces: None,
        },
        BuildingDef {
            id: id_gen.next_building_id(),
            name: "Stock Exchange",
            cost: 390,
            maintenance: 0,
            yields: YieldBundle::new().with(YieldType::Gold, 7),
            requires_district: Some("Commercial Hub"),
            great_work_slots: vec![],
            exclusive_to: None,
            replaces: None,
        },
        // ── Harbor Buildings (3) ─────────────────────────────────────────────
        BuildingDef {
            id: id_gen.next_building_id(),
            name: "Lighthouse",
            cost: 120,
            maintenance: 0,
            yields: YieldBundle::new()
                .with(YieldType::Food, 1)
                .with(YieldType::Gold, 1)
                .with(YieldType::Housing, 1),
            requires_district: Some("Harbor"),
            great_work_slots: vec![],
            exclusive_to: None,
            replaces: None,
        },
        BuildingDef {
            id: id_gen.next_building_id(),
            name: "Shipyard",
            cost: 290,
            maintenance: 0,
            yields: YieldBundle::new().with(YieldType::Production, 1),
            requires_district: Some("Harbor"),
            great_work_slots: vec![],
            exclusive_to: None,
            replaces: None,
        },
        BuildingDef {
            id: id_gen.next_building_id(),
            name: "Seaport",
            cost: 580,
            maintenance: 0,
            yields: YieldBundle::new()
                .with(YieldType::Gold, 2)
                .with(YieldType::Food, 1)
                .with(YieldType::Housing, 1),
            requires_district: Some("Harbor"),
            great_work_slots: vec![],
            exclusive_to: None,
            replaces: None,
        },
        // ── Encampment Buildings (4) ─────────────────────────────────────────
        BuildingDef {
            id: id_gen.next_building_id(),
            name: "Barracks",
            cost: 90,
            maintenance: 1,
            yields: YieldBundle::new().with(YieldType::Housing, 1),
            requires_district: Some("Encampment"),
            great_work_slots: vec![],
            exclusive_to: None,
            replaces: None,
        },
        BuildingDef {
            id: id_gen.next_building_id(),
            name: "Stable",
            cost: 120,
            maintenance: 1,
            yields: YieldBundle::new().with(YieldType::Housing, 1),
            requires_district: Some("Encampment"),
            great_work_slots: vec![],
            exclusive_to: None,
            replaces: None,
        },
        BuildingDef {
            id: id_gen.next_building_id(),
            name: "Armory",
            cost: 195,
            maintenance: 2,
            yields: YieldBundle::new(),
            requires_district: Some("Encampment"),
            great_work_slots: vec![],
            exclusive_to: None,
            replaces: None,
        },
        BuildingDef {
            id: id_gen.next_building_id(),
            name: "Military Academy",
            cost: 390,
            maintenance: 3,
            yields: YieldBundle::new().with(YieldType::Housing, 1),
            requires_district: Some("Encampment"),
            great_work_slots: vec![],
            exclusive_to: None,
            replaces: None,
        },
        // ── Industrial Zone Buildings (3) ────────────────────────────────────
        BuildingDef {
            id: id_gen.next_building_id(),
            name: "Workshop",
            cost: 195,
            maintenance: 1,
            yields: YieldBundle::new().with(YieldType::Production, 2),
            requires_district: Some("Industrial Zone"),
            great_work_slots: vec![],
            exclusive_to: None,
            replaces: None,
        },
        BuildingDef {
            id: id_gen.next_building_id(),
            name: "Factory",
            cost: 390,
            maintenance: 2,
            yields: YieldBundle::new().with(YieldType::Production, 3),
            requires_district: Some("Industrial Zone"),
            great_work_slots: vec![],
            exclusive_to: None,
            replaces: None,
        },
        BuildingDef {
            id: id_gen.next_building_id(),
            name: "Power Plant",
            cost: 580,
            maintenance: 3,
            yields: YieldBundle::new().with(YieldType::Production, 4),
            requires_district: Some("Industrial Zone"),
            great_work_slots: vec![],
            exclusive_to: None,
            replaces: None,
        },
        // ── Entertainment Complex Buildings (3) ──────────────────────────────
        BuildingDef {
            id: id_gen.next_building_id(),
            name: "Arena",
            cost: 150,
            maintenance: 1,
            yields: YieldBundle::new().with(YieldType::Amenities, 2),
            requires_district: Some("Entertainment Complex"),
            great_work_slots: vec![],
            exclusive_to: None,
            replaces: None,
        },
        BuildingDef {
            id: id_gen.next_building_id(),
            name: "Zoo",
            cost: 445,
            maintenance: 2,
            yields: YieldBundle::new().with(YieldType::Amenities, 1),
            requires_district: Some("Entertainment Complex"),
            great_work_slots: vec![],
            exclusive_to: None,
            replaces: None,
        },
        BuildingDef {
            id: id_gen.next_building_id(),
            name: "Stadium",
            cost: 660,
            maintenance: 3,
            yields: YieldBundle::new().with(YieldType::Amenities, 2),
            requires_district: Some("Entertainment Complex"),
            great_work_slots: vec![],
            exclusive_to: None,
            replaces: None,
        },
        // ── Theater Square Buildings (3) ─────────────────────────────────────
        BuildingDef {
            id: id_gen.next_building_id(),
            name: "Amphitheater",
            cost: 150,
            maintenance: 1,
            yields: YieldBundle::new().with(YieldType::Culture, 2),
            requires_district: Some("Theater Square"),
            great_work_slots: vec![
                GreatWorkSlotType::Writing,
                GreatWorkSlotType::Writing,
            ],
            exclusive_to: None,
            replaces: None,
        },
        BuildingDef {
            id: id_gen.next_building_id(),
            name: "Art Museum",
            cost: 290,
            maintenance: 2,
            yields: YieldBundle::new().with(YieldType::Culture, 1),
            requires_district: Some("Theater Square"),
            great_work_slots: vec![
                GreatWorkSlotType::Art,
                GreatWorkSlotType::Art,
                GreatWorkSlotType::Art,
            ],
            exclusive_to: None,
            replaces: None,
        },
        BuildingDef {
            id: id_gen.next_building_id(),
            name: "Broadcast Center",
            cost: 580,
            maintenance: 3,
            yields: YieldBundle::new().with(YieldType::Culture, 1),
            requires_district: Some("Theater Square"),
            great_work_slots: vec![GreatWorkSlotType::Music],
            exclusive_to: None,
            replaces: None,
        },
        // ── Aerodrome Buildings (2) ──────────────────────────────────────────
        BuildingDef {
            id: id_gen.next_building_id(),
            name: "Hangar",
            cost: 465,
            maintenance: 2,
            yields: YieldBundle::new(),
            requires_district: Some("Aerodrome"),
            great_work_slots: vec![],
            exclusive_to: None,
            replaces: None,
        },
        BuildingDef {
            id: id_gen.next_building_id(),
            name: "Airport",
            cost: 600,
            maintenance: 3,
            yields: YieldBundle::new().with(YieldType::Tourism, 1),
            requires_district: Some("Aerodrome"),
            great_work_slots: vec![],
            exclusive_to: None,
            replaces: None,
        },
    ]
}
