use crate::civ::civ_identity::BuiltinCiv;
use crate::civ::great_works::GreatWorkSlotType;
use crate::game::state::BuildingDef;
use crate::game::IdGenerator;
use crate::{YieldBundle, YieldType};

/// Returns all base-game building definitions.
pub fn builtin_building_defs(id_gen: &mut IdGenerator) -> Vec<BuildingDef> {
    vec![
        // ── City Center Buildings (8) ────────────────────────────────────────
        BuildingDef {
            id: id_gen.next_building_id(),
            name: "Monument",
            cost: 60,
            maintenance: 0,
            yields: YieldBundle::new().with(YieldType::Culture, 2),
            requires_district: Some("City Center"),
            prereq_building: None,
            mutually_exclusive: None,
            great_work_slots: vec![],
            exclusive_to: None,
            replaces: None,
            power_cost: 0, power_generated: 0, co2_per_turn: 0,
        },
        BuildingDef {
            id: id_gen.next_building_id(),
            name: "Palace",
            cost: 1,
            maintenance: 0,
            yields: YieldBundle::new()
                .with(YieldType::Gold, 5)
                .with(YieldType::Culture, 2)
                .with(YieldType::Science, 2)
                .with(YieldType::Production, 2)
                .with(YieldType::Housing, 1)
                .with(YieldType::Amenities, 1),
            requires_district: Some("City Center"),
            prereq_building: None,
            mutually_exclusive: None,
            great_work_slots: vec![],
            exclusive_to: None,
            replaces: None,
            power_cost: 0, power_generated: 0, co2_per_turn: 0,
        },
        BuildingDef {
            id: id_gen.next_building_id(),
            name: "Granary",
            cost: 65,
            maintenance: 0,
            yields: YieldBundle::new()
                .with(YieldType::Food, 1)
                .with(YieldType::Housing, 2),
            requires_district: Some("City Center"),
            prereq_building: None,
            mutually_exclusive: None,
            great_work_slots: vec![],
            exclusive_to: None,
            replaces: None,
            power_cost: 0, power_generated: 0, co2_per_turn: 0,
        },
        BuildingDef {
            id: id_gen.next_building_id(),
            name: "Walls",
            cost: 80,
            maintenance: 0,
            yields: YieldBundle::new(),
            requires_district: Some("City Center"),
            prereq_building: None,
            mutually_exclusive: None,
            great_work_slots: vec![],
            exclusive_to: None,
            replaces: None,
            power_cost: 0, power_generated: 0, co2_per_turn: 0,
        },
        BuildingDef {
            id: id_gen.next_building_id(),
            name: "Water Mill",
            cost: 80,
            maintenance: 0,
            yields: YieldBundle::new()
                .with(YieldType::Food, 1)
                .with(YieldType::Production, 1),
            requires_district: Some("City Center"),
            prereq_building: None,
            mutually_exclusive: None,
            great_work_slots: vec![],
            exclusive_to: None,
            replaces: None,
            power_cost: 0, power_generated: 0, co2_per_turn: 0,
        },
        BuildingDef {
            id: id_gen.next_building_id(),
            name: "Medieval Walls",
            cost: 225,
            maintenance: 0,
            yields: YieldBundle::new(),
            requires_district: Some("City Center"),
            prereq_building: Some("Walls"),
            mutually_exclusive: None,
            great_work_slots: vec![],
            exclusive_to: None,
            replaces: None,
            power_cost: 0, power_generated: 0, co2_per_turn: 0,
        },
        BuildingDef {
            id: id_gen.next_building_id(),
            name: "Renaissance Walls",
            cost: 305,
            maintenance: 0,
            yields: YieldBundle::new(),
            requires_district: Some("City Center"),
            prereq_building: Some("Medieval Walls"),
            mutually_exclusive: None,
            great_work_slots: vec![],
            exclusive_to: None,
            replaces: None,
            power_cost: 0, power_generated: 0, co2_per_turn: 0,
        },
        BuildingDef {
            id: id_gen.next_building_id(),
            name: "Sewer",
            cost: 200,
            maintenance: 0,
            yields: YieldBundle::new().with(YieldType::Housing, 2),
            requires_district: Some("City Center"),
            prereq_building: None,
            mutually_exclusive: None,
            great_work_slots: vec![],
            exclusive_to: None,
            replaces: None,
            power_cost: 0, power_generated: 0, co2_per_turn: 0,
        },
        // ── Campus Buildings (3) ─────────────────────────────────────────────
        BuildingDef {
            id: id_gen.next_building_id(),
            name: "Library",
            cost: 90,
            maintenance: 1,
            yields: YieldBundle::new().with(YieldType::Science, 2),
            requires_district: Some("Campus"),
            prereq_building: None,
            mutually_exclusive: None,
            great_work_slots: vec![],
            exclusive_to: None,
            replaces: None,
            power_cost: 0, power_generated: 0, co2_per_turn: 0,
        },
        BuildingDef {
            id: id_gen.next_building_id(),
            name: "University",
            cost: 250,
            maintenance: 2,
            yields: YieldBundle::new()
                .with(YieldType::Science, 4)
                .with(YieldType::Housing, 1),
            requires_district: Some("Campus"),
            prereq_building: Some("Library"),
            mutually_exclusive: None,
            great_work_slots: vec![],
            exclusive_to: None,
            replaces: None,
            power_cost: 0, power_generated: 0, co2_per_turn: 0,
        },
        BuildingDef {
            id: id_gen.next_building_id(),
            name: "Research Lab",
            cost: 580,
            maintenance: 3,
            yields: YieldBundle::new().with(YieldType::Science, 5),
            requires_district: Some("Campus"),
            prereq_building: Some("University"),
            mutually_exclusive: None,
            great_work_slots: vec![],
            exclusive_to: None,
            replaces: None,
            power_cost: 1, power_generated: 0, co2_per_turn: 0,
        },
        // ── Holy Site Buildings (3) ──────────────────────────────────────────
        BuildingDef {
            id: id_gen.next_building_id(),
            name: "Shrine",
            cost: 70,
            maintenance: 1,
            yields: YieldBundle::new().with(YieldType::Faith, 2),
            requires_district: Some("Holy Site"),
            prereq_building: None,
            mutually_exclusive: None,
            great_work_slots: vec![],
            exclusive_to: None,
            replaces: None,
            power_cost: 0, power_generated: 0, co2_per_turn: 0,
        },
        BuildingDef {
            id: id_gen.next_building_id(),
            name: "Temple",
            cost: 120,
            maintenance: 2,
            yields: YieldBundle::new().with(YieldType::Faith, 4),
            requires_district: Some("Holy Site"),
            prereq_building: Some("Shrine"),
            mutually_exclusive: None,
            great_work_slots: vec![],
            exclusive_to: None,
            replaces: None,
            power_cost: 0, power_generated: 0, co2_per_turn: 0,
        },
        BuildingDef {
            id: id_gen.next_building_id(),
            name: "Stave Church",
            cost: 120,
            maintenance: 2,
            yields: YieldBundle::new().with(YieldType::Faith, 4),
            requires_district: Some("Holy Site"),
            prereq_building: Some("Shrine"),
            mutually_exclusive: None,
            great_work_slots: vec![],
            exclusive_to: Some(BuiltinCiv::Norway),
            replaces: Some("Temple"),
            power_cost: 0, power_generated: 0, co2_per_turn: 0,
        },
        // ── Holy Site Worship Buildings (9) ──────────────────────────────────
        // Worship buildings are unlocked via a religion belief; one per religion.
        // All cost 190 and require a Holy Site.
        BuildingDef {
            id: id_gen.next_building_id(),
            name: "Cathedral",
            cost: 190,
            maintenance: 2,
            yields: YieldBundle::new().with(YieldType::Faith, 3),
            requires_district: Some("Holy Site"),
            prereq_building: Some("Temple"),
            mutually_exclusive: None,
            great_work_slots: vec![GreatWorkSlotType::Art],
            exclusive_to: None,
            replaces: None,
            power_cost: 0, power_generated: 0, co2_per_turn: 0,
        },
        BuildingDef {
            id: id_gen.next_building_id(),
            name: "Gurdwara",
            cost: 190,
            maintenance: 2,
            yields: YieldBundle::new()
                .with(YieldType::Faith, 3)
                .with(YieldType::Food, 2),
            requires_district: Some("Holy Site"),
            prereq_building: Some("Temple"),
            mutually_exclusive: None,
            great_work_slots: vec![],
            exclusive_to: None,
            replaces: None,
            power_cost: 0, power_generated: 0, co2_per_turn: 0,
        },
        BuildingDef {
            id: id_gen.next_building_id(),
            name: "Meeting House",
            cost: 190,
            maintenance: 2,
            yields: YieldBundle::new()
                .with(YieldType::Faith, 3)
                .with(YieldType::Production, 2),
            requires_district: Some("Holy Site"),
            prereq_building: Some("Temple"),
            mutually_exclusive: None,
            great_work_slots: vec![],
            exclusive_to: None,
            replaces: None,
            power_cost: 0, power_generated: 0, co2_per_turn: 0,
        },
        BuildingDef {
            id: id_gen.next_building_id(),
            name: "Mosque",
            cost: 190,
            maintenance: 2,
            yields: YieldBundle::new().with(YieldType::Faith, 3),
            requires_district: Some("Holy Site"),
            prereq_building: Some("Temple"),
            mutually_exclusive: None,
            great_work_slots: vec![],
            exclusive_to: None,
            replaces: None,
            power_cost: 0, power_generated: 0, co2_per_turn: 0,
        },
        BuildingDef {
            id: id_gen.next_building_id(),
            name: "Pagoda",
            cost: 190,
            maintenance: 2,
            yields: YieldBundle::new()
                .with(YieldType::Faith, 3)
                .with(YieldType::Housing, 1),
            requires_district: Some("Holy Site"),
            prereq_building: Some("Temple"),
            mutually_exclusive: None,
            great_work_slots: vec![],
            exclusive_to: None,
            replaces: None,
            power_cost: 0, power_generated: 0, co2_per_turn: 0,
        },
        BuildingDef {
            id: id_gen.next_building_id(),
            name: "Synagogue",
            cost: 190,
            maintenance: 2,
            yields: YieldBundle::new().with(YieldType::Faith, 5),
            requires_district: Some("Holy Site"),
            prereq_building: Some("Temple"),
            mutually_exclusive: None,
            great_work_slots: vec![],
            exclusive_to: None,
            replaces: None,
            power_cost: 0, power_generated: 0, co2_per_turn: 0,
        },
        BuildingDef {
            id: id_gen.next_building_id(),
            name: "Wat",
            cost: 190,
            maintenance: 2,
            yields: YieldBundle::new()
                .with(YieldType::Faith, 3)
                .with(YieldType::Science, 2),
            requires_district: Some("Holy Site"),
            prereq_building: Some("Temple"),
            mutually_exclusive: None,
            great_work_slots: vec![],
            exclusive_to: None,
            replaces: None,
            power_cost: 0, power_generated: 0, co2_per_turn: 0,
        },
        BuildingDef {
            id: id_gen.next_building_id(),
            name: "Stupa",
            cost: 190,
            maintenance: 2,
            yields: YieldBundle::new()
                .with(YieldType::Faith, 3)
                .with(YieldType::Amenities, 1),
            requires_district: Some("Holy Site"),
            prereq_building: Some("Temple"),
            mutually_exclusive: None,
            great_work_slots: vec![],
            exclusive_to: None,
            replaces: None,
            power_cost: 0, power_generated: 0, co2_per_turn: 0,
        },
        BuildingDef {
            id: id_gen.next_building_id(),
            name: "Dar-e Mehr",
            cost: 190,
            maintenance: 2,
            yields: YieldBundle::new()
                .with(YieldType::Faith, 3)
                .with(YieldType::Culture, 1),
            requires_district: Some("Holy Site"),
            prereq_building: Some("Temple"),
            mutually_exclusive: None,
            great_work_slots: vec![],
            exclusive_to: None,
            replaces: None,
            power_cost: 0, power_generated: 0, co2_per_turn: 0,
        },
        // ── Commercial Hub Buildings (3) ─────────────────────────────────────
        BuildingDef {
            id: id_gen.next_building_id(),
            name: "Market",
            cost: 120,
            maintenance: 0,
            yields: YieldBundle::new().with(YieldType::Gold, 3),
            requires_district: Some("Commercial Hub"),
            prereq_building: None,
            mutually_exclusive: None,
            great_work_slots: vec![],
            exclusive_to: None,
            replaces: None,
            power_cost: 0, power_generated: 0, co2_per_turn: 0,
        },
        BuildingDef {
            id: id_gen.next_building_id(),
            name: "Bank",
            cost: 290,
            maintenance: 0,
            yields: YieldBundle::new().with(YieldType::Gold, 5),
            requires_district: Some("Commercial Hub"),
            prereq_building: Some("Market"),
            mutually_exclusive: None,
            great_work_slots: vec![],
            exclusive_to: None,
            replaces: None,
            power_cost: 0, power_generated: 0, co2_per_turn: 0,
        },
        BuildingDef {
            id: id_gen.next_building_id(),
            name: "Stock Exchange",
            cost: 390,
            maintenance: 0,
            yields: YieldBundle::new().with(YieldType::Gold, 7),
            requires_district: Some("Commercial Hub"),
            prereq_building: Some("Bank"),
            mutually_exclusive: None,
            great_work_slots: vec![],
            exclusive_to: None,
            replaces: None,
            power_cost: 0, power_generated: 0, co2_per_turn: 0,
        },
        // ── Harbor Buildings (3) ─────────────────────────────────────────────
        BuildingDef {
            id: id_gen.next_building_id(),
            name: "Lighthouse",
            cost: 120,
            maintenance: 0,
            yields: YieldBundle::new()
                .with(YieldType::Food, 1)
                .with(YieldType::Gold, 1)
                .with(YieldType::Housing, 1),
            requires_district: Some("Harbor"),
            prereq_building: None,
            mutually_exclusive: None,
            great_work_slots: vec![],
            exclusive_to: None,
            replaces: None,
            power_cost: 0, power_generated: 0, co2_per_turn: 0,
        },
        BuildingDef {
            id: id_gen.next_building_id(),
            name: "Shipyard",
            cost: 290,
            maintenance: 0,
            yields: YieldBundle::new().with(YieldType::Production, 1),
            requires_district: Some("Harbor"),
            prereq_building: Some("Lighthouse"),
            mutually_exclusive: None,
            great_work_slots: vec![],
            exclusive_to: None,
            replaces: None,
            power_cost: 0, power_generated: 0, co2_per_turn: 0,
        },
        BuildingDef {
            id: id_gen.next_building_id(),
            name: "Seaport",
            cost: 580,
            maintenance: 0,
            yields: YieldBundle::new()
                .with(YieldType::Gold, 2)
                .with(YieldType::Food, 1)
                .with(YieldType::Housing, 1),
            requires_district: Some("Harbor"),
            prereq_building: Some("Shipyard"),
            mutually_exclusive: None,
            great_work_slots: vec![],
            exclusive_to: None,
            replaces: None,
            power_cost: 0, power_generated: 0, co2_per_turn: 0,
        },
        // ── Encampment Buildings (4) ─────────────────────────────────────────
        BuildingDef {
            id: id_gen.next_building_id(),
            name: "Barracks",
            cost: 90,
            maintenance: 1,
            yields: YieldBundle::new().with(YieldType::Housing, 1),
            requires_district: Some("Encampment"),
            prereq_building: None,
            mutually_exclusive: Some("Stable"),
            great_work_slots: vec![],
            exclusive_to: None,
            replaces: None,
            power_cost: 0, power_generated: 0, co2_per_turn: 0,
        },
        BuildingDef {
            id: id_gen.next_building_id(),
            name: "Stable",
            cost: 120,
            maintenance: 1,
            yields: YieldBundle::new().with(YieldType::Housing, 1),
            requires_district: Some("Encampment"),
            prereq_building: None,
            mutually_exclusive: Some("Barracks"),
            great_work_slots: vec![],
            exclusive_to: None,
            replaces: None,
            power_cost: 0, power_generated: 0, co2_per_turn: 0,
        },
        BuildingDef {
            id: id_gen.next_building_id(),
            name: "Armory",
            cost: 195,
            maintenance: 2,
            yields: YieldBundle::new(),
            requires_district: Some("Encampment"),
            prereq_building: Some("Barracks"),
            mutually_exclusive: None,
            great_work_slots: vec![],
            exclusive_to: None,
            replaces: None,
            power_cost: 0, power_generated: 0, co2_per_turn: 0,
        },
        BuildingDef {
            id: id_gen.next_building_id(),
            name: "Military Academy",
            cost: 390,
            maintenance: 3,
            yields: YieldBundle::new().with(YieldType::Housing, 1),
            requires_district: Some("Encampment"),
            prereq_building: Some("Armory"),
            mutually_exclusive: None,
            great_work_slots: vec![],
            exclusive_to: None,
            replaces: None,
            power_cost: 0, power_generated: 0, co2_per_turn: 0,
        },
        // ── Industrial Zone Buildings (3) ────────────────────────────────────
        BuildingDef {
            id: id_gen.next_building_id(),
            name: "Workshop",
            cost: 195,
            maintenance: 1,
            yields: YieldBundle::new().with(YieldType::Production, 2),
            requires_district: Some("Industrial Zone"),
            prereq_building: None,
            mutually_exclusive: None,
            great_work_slots: vec![],
            exclusive_to: None,
            replaces: None,
            power_cost: 0, power_generated: 0, co2_per_turn: 0,
        },
        BuildingDef {
            id: id_gen.next_building_id(),
            name: "Factory",
            cost: 390,
            maintenance: 2,
            yields: YieldBundle::new().with(YieldType::Production, 3),
            requires_district: Some("Industrial Zone"),
            prereq_building: Some("Workshop"),
            mutually_exclusive: None,
            great_work_slots: vec![],
            exclusive_to: None,
            replaces: None,
            power_cost: 1, power_generated: 0, co2_per_turn: 0,
        },
        BuildingDef {
            id: id_gen.next_building_id(),
            name: "Power Plant",
            cost: 580,
            maintenance: 3,
            yields: YieldBundle::new().with(YieldType::Production, 4),
            requires_district: Some("Industrial Zone"),
            prereq_building: Some("Factory"),
            mutually_exclusive: None,
            great_work_slots: vec![],
            exclusive_to: None,
            replaces: None,
            power_cost: 0, power_generated: 0, co2_per_turn: 0,
        },
        // ── Entertainment Complex Buildings (3) ──────────────────────────────
        BuildingDef {
            id: id_gen.next_building_id(),
            name: "Arena",
            cost: 150,
            maintenance: 1,
            yields: YieldBundle::new().with(YieldType::Amenities, 2),
            requires_district: Some("Entertainment Complex"),
            prereq_building: None,
            mutually_exclusive: None,
            great_work_slots: vec![],
            exclusive_to: None,
            replaces: None,
            power_cost: 0, power_generated: 0, co2_per_turn: 0,
        },
        BuildingDef {
            id: id_gen.next_building_id(),
            name: "Zoo",
            cost: 445,
            maintenance: 2,
            yields: YieldBundle::new().with(YieldType::Amenities, 1),
            requires_district: Some("Entertainment Complex"),
            prereq_building: Some("Arena"),
            mutually_exclusive: None,
            great_work_slots: vec![],
            exclusive_to: None,
            replaces: None,
            power_cost: 0, power_generated: 0, co2_per_turn: 0,
        },
        BuildingDef {
            id: id_gen.next_building_id(),
            name: "Stadium",
            cost: 660,
            maintenance: 3,
            yields: YieldBundle::new().with(YieldType::Amenities, 2),
            requires_district: Some("Entertainment Complex"),
            prereq_building: Some("Zoo"),
            mutually_exclusive: None,
            great_work_slots: vec![],
            exclusive_to: None,
            replaces: None,
            power_cost: 0, power_generated: 0, co2_per_turn: 0,
        },
        // ── Theater Square Buildings (4) ─────────────────────────────────────
        BuildingDef {
            id: id_gen.next_building_id(),
            name: "Amphitheater",
            cost: 150,
            maintenance: 1,
            yields: YieldBundle::new().with(YieldType::Culture, 2),
            requires_district: Some("Theater Square"),
            prereq_building: None,
            mutually_exclusive: None,
            great_work_slots: vec![
                GreatWorkSlotType::Writing,
                GreatWorkSlotType::Writing,
            ],
            exclusive_to: None,
            replaces: None,
            power_cost: 0, power_generated: 0, co2_per_turn: 0,
        },
        BuildingDef {
            id: id_gen.next_building_id(),
            name: "Art Museum",
            cost: 290,
            maintenance: 2,
            yields: YieldBundle::new().with(YieldType::Culture, 1),
            requires_district: Some("Theater Square"),
            prereq_building: Some("Amphitheater"),
            mutually_exclusive: Some("Archaeological Museum"),
            great_work_slots: vec![
                GreatWorkSlotType::Art,
                GreatWorkSlotType::Art,
                GreatWorkSlotType::Art,
            ],
            exclusive_to: None,
            replaces: None,
            power_cost: 0, power_generated: 0, co2_per_turn: 0,
        },
        BuildingDef {
            id: id_gen.next_building_id(),
            name: "Archaeological Museum",
            cost: 290,
            maintenance: 2,
            yields: YieldBundle::new().with(YieldType::Culture, 1),
            requires_district: Some("Theater Square"),
            prereq_building: Some("Amphitheater"),
            mutually_exclusive: Some("Art Museum"),
            great_work_slots: vec![
                GreatWorkSlotType::Any,
                GreatWorkSlotType::Any,
                GreatWorkSlotType::Any,
            ],
            exclusive_to: None,
            replaces: None,
            power_cost: 0, power_generated: 0, co2_per_turn: 0,
        },
        BuildingDef {
            id: id_gen.next_building_id(),
            name: "Broadcast Center",
            cost: 580,
            maintenance: 3,
            yields: YieldBundle::new().with(YieldType::Culture, 1),
            requires_district: Some("Theater Square"),
            prereq_building: Some("Art Museum"),
            mutually_exclusive: None,
            great_work_slots: vec![GreatWorkSlotType::Music],
            exclusive_to: None,
            replaces: None,
            power_cost: 1, power_generated: 0, co2_per_turn: 0,
        },
        // ── Aerodrome Buildings (2) ──────────────────────────────────────────
        BuildingDef {
            id: id_gen.next_building_id(),
            name: "Hangar",
            cost: 465,
            maintenance: 2,
            yields: YieldBundle::new(),
            requires_district: Some("Aerodrome"),
            prereq_building: None,
            mutually_exclusive: None,
            great_work_slots: vec![],
            exclusive_to: None,
            replaces: None,
            power_cost: 0, power_generated: 0, co2_per_turn: 0,
        },
        BuildingDef {
            id: id_gen.next_building_id(),
            name: "Airport",
            cost: 600,
            maintenance: 3,
            yields: YieldBundle::new().with(YieldType::Tourism, 1),
            requires_district: Some("Aerodrome"),
            prereq_building: Some("Hangar"),
            mutually_exclusive: None,
            great_work_slots: vec![],
            exclusive_to: None,
            replaces: None,
            power_cost: 0, power_generated: 0, co2_per_turn: 0,
        },
        // ── GS Power Plant Buildings ────────────────────────────────────────
        BuildingDef {
            id: id_gen.next_building_id(),
            name: "Coal Power Plant",
            cost: 580,
            maintenance: 3,
            yields: YieldBundle::new(),
            requires_district: Some("Industrial Zone"),
            prereq_building: Some("Workshop"),
            mutually_exclusive: None,
            great_work_slots: vec![],
            exclusive_to: None,
            replaces: None,
            power_cost: 0, power_generated: 4, co2_per_turn: 1,
        },
        BuildingDef {
            id: id_gen.next_building_id(),
            name: "Oil Power Plant",
            cost: 580,
            maintenance: 3,
            yields: YieldBundle::new(),
            requires_district: Some("Industrial Zone"),
            prereq_building: Some("Workshop"),
            mutually_exclusive: None,
            great_work_slots: vec![],
            exclusive_to: None,
            replaces: None,
            power_cost: 0, power_generated: 4, co2_per_turn: 1,
        },
        BuildingDef {
            id: id_gen.next_building_id(),
            name: "Nuclear Power Plant",
            cost: 580,
            maintenance: 3,
            yields: YieldBundle::new(),
            requires_district: Some("Industrial Zone"),
            prereq_building: Some("Factory"),
            mutually_exclusive: None,
            great_work_slots: vec![],
            exclusive_to: None,
            replaces: None,
            power_cost: 0, power_generated: 16, co2_per_turn: 0,
        },
        // ── GS Additional City Center Buildings ─────────────────────────────
        BuildingDef {
            id: id_gen.next_building_id(),
            name: "Flood Barrier",
            cost: 400,
            maintenance: 0,
            yields: YieldBundle::new(),
            requires_district: Some("City Center"),
            prereq_building: None,
            mutually_exclusive: None,
            great_work_slots: vec![],
            exclusive_to: None,
            replaces: None,
            power_cost: 0, power_generated: 0, co2_per_turn: 0,
        },
        BuildingDef {
            id: id_gen.next_building_id(),
            name: "Food Market",
            cost: 290,
            maintenance: 1,
            yields: YieldBundle::new(),
            requires_district: Some("City Center"),
            prereq_building: Some("Granary"),
            mutually_exclusive: None,
            great_work_slots: vec![],
            exclusive_to: None,
            replaces: None,
            power_cost: 0, power_generated: 0, co2_per_turn: 0,
        },
        BuildingDef {
            id: id_gen.next_building_id(),
            name: "Shopping Mall",
            cost: 390,
            maintenance: 1,
            yields: YieldBundle::new(),
            requires_district: Some("City Center"),
            prereq_building: Some("Market"),
            mutually_exclusive: None,
            great_work_slots: vec![],
            exclusive_to: None,
            replaces: None,
            power_cost: 0, power_generated: 0, co2_per_turn: 0,
        },
        // ── DLC Civilization Pack unique buildings ───────────────────────────
        BuildingDef {
            id: id_gen.next_building_id(),
            name: "Tlachtli",
            cost: 150,
            maintenance: 1,
            yields: YieldBundle::new().with(YieldType::Faith, 2).with(YieldType::Culture, 1),
            requires_district: Some("Entertainment Complex"),
            prereq_building: None,
            mutually_exclusive: None,
            great_work_slots: vec![],
            exclusive_to: Some(BuiltinCiv::Aztec),
            replaces: Some("Arena"),
            power_cost: 0, power_generated: 0, co2_per_turn: 0,
        },
        BuildingDef {
            id: id_gen.next_building_id(),
            name: "Prasat",
            cost: 120,
            maintenance: 2,
            yields: YieldBundle::new().with(YieldType::Faith, 3),
            requires_district: Some("Holy Site"),
            prereq_building: Some("Shrine"),
            mutually_exclusive: None,
            great_work_slots: vec![],
            exclusive_to: Some(BuiltinCiv::Khmer),
            replaces: Some("Temple"),
            power_cost: 0, power_generated: 0, co2_per_turn: 0,
        },
        BuildingDef {
            id: id_gen.next_building_id(),
            name: "Basilikoi Paides",
            cost: 90,
            maintenance: 1,
            yields: YieldBundle::new().with(YieldType::Production, 1),
            requires_district: Some("Encampment"),
            prereq_building: None,
            mutually_exclusive: None,
            great_work_slots: vec![],
            exclusive_to: Some(BuiltinCiv::Macedon),
            replaces: Some("Barracks"),
            power_cost: 0, power_generated: 0, co2_per_turn: 0,
        },
        BuildingDef {
            id: id_gen.next_building_id(),
            name: "Sukiennice",
            cost: 120,
            maintenance: 0,
            yields: YieldBundle::new().with(YieldType::Gold, 3).with(YieldType::Production, 2),
            requires_district: Some("Commercial Hub"),
            prereq_building: None,
            mutually_exclusive: None,
            great_work_slots: vec![],
            exclusive_to: Some(BuiltinCiv::Poland),
            replaces: Some("Market"),
            power_cost: 0, power_generated: 0, co2_per_turn: 0,
        },
        BuildingDef {
            id: id_gen.next_building_id(),
            name: "Navigation School",
            cost: 250,
            maintenance: 2,
            yields: YieldBundle::new().with(YieldType::Science, 4),
            requires_district: Some("Campus"),
            prereq_building: Some("Library"),
            mutually_exclusive: None,
            great_work_slots: vec![],
            exclusive_to: Some(BuiltinCiv::Portugal),
            replaces: Some("University"),
            power_cost: 0, power_generated: 0, co2_per_turn: 0,
        },
    ]
}
