pub mod climate;
pub mod disaster;
pub mod edge;
pub mod feature;
pub mod improvement;
pub mod mapgen;
pub mod resource;
pub mod road;
pub mod terrain;
pub mod tile;
pub mod wonder;

pub use climate::CLIMATE_THRESHOLDS;
pub use disaster::DisasterKind;
pub use edge::{BuiltinEdgeFeature, EdgeFeatureDef, WorldEdge};
pub use feature::BuiltinFeature;
pub use improvement::{BuiltinImprovement, ElevationReq, ImprovementRequirements, ProximityReq};
pub use resource::BuiltinResource;
pub use road::{BuiltinRoad, RoadDef};
pub use terrain::BuiltinTerrain;
pub use tile::WorldTile;
pub use wonder::{BuiltinNaturalWonder, NaturalWonder};
