//! Barbarian camps and barbarian clans game mode.
//!
//! ## Base Barbarian Mechanic
//! - Camps spawn on unclaimed land tiles away from cities.
//! - Each camp spawns a scout that explores the map.
//! - When a scout discovers a player civilization, it returns to the camp.
//! - Once the scout returns, the camp begins generating combat units.
//!
//! ## Barbarian Clans Mode
//! When enabled, camps belong to a clan type and offer diplomacy:
//! - **Hire**: Pay gold to recruit a unit from the camp (with cooldown).
//! - **Bribe**: Pay gold so the clan will not attack you (bonus to city-state conversion).
//! - **Incite**: Pay gold to make the clan attack another player (debuff to conversion).
//! - Camps can convert to city-states after sufficient turns if city-placement rules are met.

use crate::{CivId, UnitId};
use libhexgrid::coord::HexCoord;

/// Unique identifier for a barbarian camp.
/// Defined in `ids.rs` via `define_id!(BarbarianCampId)`.
pub use crate::BarbarianCampId;

/// The functional type of a barbarian clan (Barbarian Clans mode only).
/// Determines the unit types the camp can produce and the city-state type
/// it converts into.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub enum ClanType {
    /// Produces melee infantry. Converts to Militaristic city-state.
    Melee,
    /// Produces ranged units. Converts to Scientific city-state.
    Ranged,
    /// Produces cavalry/mounted units. Converts to Trade city-state.
    Cavalry,
    /// Produces naval units (coastal camps). Converts to Industrial city-state.
    Naval,
    /// Produces siege units. Converts to Cultural city-state.
    Siege,
}

/// Lifecycle state of the camp's scout.
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub enum ScoutState {
    /// Scout has not yet been spawned. The camp will spawn one on the next
    /// barbarian turn phase.
    NotSpawned,
    /// Scout is exploring the map. Contains the scout's `UnitId`.
    Exploring { scout_id: UnitId },
    /// Scout has discovered a player civilization and is returning to camp.
    Returning { scout_id: UnitId, discovered_civ: CivId },
    /// Scout has returned to camp. The camp may now generate combat units.
    /// `discovered_civs` tracks which players the camp is aware of.
    Returned { discovered_civs: Vec<CivId> },
}

/// How a player has interacted with a barbarian clan (Clans mode).
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub enum ClanInteraction {
    /// The player hired a unit. Includes the turn the hire occurred for cooldown.
    Hired { turn: u32 },
    /// The player bribed the clan not to attack. Active until `expires_turn`.
    Bribed { expires_turn: u32 },
    /// The player incited the clan against a target. Active until `expires_turn`.
    Incited { target: CivId, expires_turn: u32 },
}

/// A barbarian camp on the world map.
#[derive(Debug, Clone)]
pub struct BarbarianCamp {
    pub id: BarbarianCampId,
    pub coord: HexCoord,
    /// The CivId representing the barbarian faction that owns this camp's units.
    pub owner: CivId,
    /// Turn on which the camp was placed.
    pub spawned_turn: u32,
    /// Current state of the camp's scout.
    pub scout_state: ScoutState,
    /// Combat units generated by this camp (tracked for despawn on camp destruction).
    pub spawned_units: Vec<UnitId>,
    /// Number of combat units spawned so far.
    pub units_spawned_count: u32,
    /// Turns since the scout returned. Used to pace unit generation.
    pub turns_since_scout_returned: u32,

    // ── Barbarian Clans mode fields (ignored when clans mode is off) ─────
    /// Clan type. `None` when barbarian clans mode is disabled.
    pub clan_type: Option<ClanType>,
    /// Per-player interactions (hire / bribe / incite) in clans mode.
    pub clan_interactions: Vec<(CivId, ClanInteraction)>,
    /// Accumulated "conversion progress" toward becoming a city-state.
    /// Increases each turn; bribes accelerate it, incitements slow it.
    pub conversion_progress: u32,
    /// Whether this camp has already converted to a city-state.
    pub converted: bool,
}

/// Configuration for the barbarian system, stored in `GameState`.
#[derive(Debug, Clone)]
pub struct BarbarianConfig {
    /// Whether barbarians are enabled at all.
    pub enabled: bool,
    /// Whether the Barbarian Clans game mode is active.
    pub clans_mode: bool,
    /// Minimum distance from any city center for camp spawning.
    pub min_distance_from_city: u32,
    /// Minimum distance between barbarian camps.
    pub min_distance_between_camps: u32,
    /// Maximum number of camps on the map at once.
    pub max_camps: usize,
    /// Turns between camp spawn attempts.
    pub spawn_interval: u32,
    /// Turns between unit generation once the scout has returned.
    pub unit_generation_interval: u32,
    /// Gold cost to hire a unit from a camp (Clans mode).
    pub hire_cost: u32,
    /// Cooldown in turns after hiring before hiring again.
    pub hire_cooldown: u32,
    /// Gold cost to bribe a clan not to attack.
    pub bribe_cost: u32,
    /// Duration of a bribe in turns.
    pub bribe_duration: u32,
    /// Gold cost to incite a clan against another player.
    pub incite_cost: u32,
    /// Duration of an incitement in turns.
    pub incite_duration: u32,
    /// Turns a camp must survive before it can convert to a city-state.
    pub conversion_threshold: u32,
    /// Conversion progress per turn (base rate).
    pub conversion_rate: u32,
    /// Bonus conversion progress per turn from a bribe.
    pub bribe_conversion_bonus: u32,
    /// Penalty to conversion progress per turn from an incitement.
    pub incite_conversion_penalty: u32,
}

impl Default for BarbarianConfig {
    fn default() -> Self {
        Self {
            enabled: true,
            clans_mode: false,
            min_distance_from_city: 7,
            min_distance_between_camps: 7,
            max_camps: 6,
            spawn_interval: 10,
            unit_generation_interval: 5,
            hire_cost: 100,
            hire_cooldown: 10,
            bribe_cost: 75,
            bribe_duration: 15,
            incite_cost: 50,
            incite_duration: 10,
            conversion_threshold: 200,
            conversion_rate: 3,
            bribe_conversion_bonus: 5,
            incite_conversion_penalty: 3,
        }
    }
}

impl BarbarianCamp {
    pub fn new(
        id: BarbarianCampId,
        coord: HexCoord,
        owner: CivId,
        spawned_turn: u32,
        clan_type: Option<ClanType>,
    ) -> Self {
        Self {
            id,
            coord,
            owner,
            spawned_turn,
            scout_state: ScoutState::NotSpawned,
            spawned_units: Vec::new(),
            units_spawned_count: 0,
            turns_since_scout_returned: 0,
            clan_type,
            clan_interactions: Vec::new(),
            conversion_progress: 0,
            converted: false,
        }
    }

    /// Returns true if this camp can generate combat units (scout has returned).
    pub fn can_generate_units(&self) -> bool {
        matches!(self.scout_state, ScoutState::Returned { .. })
    }

    /// Returns the unit type this camp should produce, based on clan type.
    /// Falls back to "Warrior" for base barbarians.
    pub fn preferred_unit_type(&self) -> &'static str {
        match self.clan_type {
            Some(ClanType::Melee) | None => "Warrior",
            Some(ClanType::Ranged) => "Archer",
            Some(ClanType::Cavalry) => "Horseman",
            Some(ClanType::Naval) => "Galley",
            Some(ClanType::Siege) => "Catapult",
        }
    }

    /// Returns the city-state type this camp would convert into.
    pub fn conversion_city_state_type(&self) -> super::city_state::CityStateType {
        use super::city_state::CityStateType;
        match self.clan_type {
            Some(ClanType::Melee) => CityStateType::Militaristic,
            Some(ClanType::Ranged) => CityStateType::Scientific,
            Some(ClanType::Cavalry) => CityStateType::Trade,
            Some(ClanType::Naval) => CityStateType::Industrial,
            Some(ClanType::Siege) => CityStateType::Cultural,
            None => CityStateType::Militaristic,
        }
    }

    /// Check if a player has an active bribe on this camp.
    pub fn is_bribed_by(&self, civ: CivId, current_turn: u32) -> bool {
        self.clan_interactions.iter().any(|(c, interaction)| {
            *c == civ && matches!(interaction, ClanInteraction::Bribed { expires_turn } if *expires_turn > current_turn)
        })
    }

    /// Check if this camp has been incited against a specific player.
    pub fn is_incited_against(&self, target: CivId, current_turn: u32) -> bool {
        self.clan_interactions.iter().any(|(_, interaction)| {
            matches!(interaction, ClanInteraction::Incited { target: t, expires_turn } if *t == target && *expires_turn > current_turn)
        })
    }

    /// Check if a player can hire from this camp (not on cooldown).
    pub fn can_hire(&self, civ: CivId, current_turn: u32, cooldown: u32) -> bool {
        !self.clan_interactions.iter().any(|(c, interaction)| {
            *c == civ && matches!(interaction, ClanInteraction::Hired { turn } if current_turn < *turn + cooldown)
        })
    }

    /// The camp's name for display (e.g., "Melee Clan" or "Barbarian Camp").
    pub fn display_name(&self) -> &'static str {
        match self.clan_type {
            Some(ClanType::Melee) => "Melee Clan",
            Some(ClanType::Ranged) => "Ranged Clan",
            Some(ClanType::Cavalry) => "Cavalry Clan",
            Some(ClanType::Naval) => "Naval Clan",
            Some(ClanType::Siege) => "Siege Clan",
            None => "Barbarian Camp",
        }
    }
}
